import sys
import openpyxl
from openpyxl.styles import (Font, PatternFill, Alignment, Border, Side,
                              GradientFill)
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation
from datetime import date

EXCEL_OUT = sys.argv[1]

wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Tracking"

# ─── Styles ──────────────────────────────────────────────────────
HDR_FILL   = PatternFill("solid", fgColor="1F3864")   # navy blue
HDR_FONT   = Font(color="FFFFFF", bold=True, size=10, name="Calibri")
DATA_FONT  = Font(size=10, name="Calibri")
ALT_FILL   = PatternFill("solid", fgColor="EBF0FA")   # very light blue
SENT_FILL  = PatternFill("solid", fgColor="E2EFDA")   # light green
RESP_FILL  = PatternFill("solid", fgColor="FFF2CC")   # light yellow
CONT_FILL  = PatternFill("solid", fgColor="FCE4D6")   # light orange
OK_FILL    = PatternFill("solid", fgColor="C6EFCE")   # strong green

thin = Side(style='thin', color="B8CCE4")
border = Border(left=thin, right=thin, top=thin, bottom=thin)

CENTER = Alignment(horizontal="center", vertical="center", wrap_text=True)
LEFT   = Alignment(horizontal="left",   vertical="center", wrap_text=True)

# ─── Columns ─────────────────────────────────────────────────────
COLS = [
    ("Publisher",         22),
    ("Group / Imprint",   18),
    ("Genres",            22),
    ("Contact type",      14),
    ("Email / URL",       36),
    ("Priority",          11),
    ("Date sent",         15),
    ("Date resent",       16),
    ("Response",          14),
    ("Response type",     18),
    ("Contract",          12),
    ("Accepted",          11),
    ("Follow-up notes",   30),
]

# ─── Book title row ──────────────────────────────────────────────
ws.merge_cells("A1:M1")
title_cell = ws["A1"]
title_cell.value = "PUBLISHER TRACKING — [BOOK TITLE]"
title_cell.font = Font(bold=True, size=13, color="1F3864", name="Calibri")
title_cell.alignment = CENTER
title_cell.fill = PatternFill("solid", fgColor="D6E4F7")
ws.row_dimensions[1].height = 28

# ─── Subtitle row ────────────────────────────────────────────────
ws.merge_cells("A2:M2")
sub = ws["A2"]
sub.value = f"Generated: {date.today().strftime('%d/%m/%Y')}  ·  Genre: [GENRE]  ·  Author: [AUTHOR]"
sub.font = Font(italic=True, size=9, color="555555", name="Calibri")
sub.alignment = CENTER
ws.row_dimensions[2].height = 18

# ─── Headers ─────────────────────────────────────────────────────
ws.row_dimensions[3].height = 40
for col_idx, (col_name, col_width) in enumerate(COLS, start=1):
    cell = ws.cell(row=3, column=col_idx, value=col_name)
    cell.fill = HDR_FILL
    cell.font = HDR_FONT
    cell.alignment = CENTER
    cell.border = border
    ws.column_dimensions[get_column_letter(col_idx)].width = col_width

ws.freeze_panes = "A4"

# ─── Publisher data (selected by genre) ──────────────────────────
# HumanInk REPLACES THIS LIST with the publishers recommended for the genre
editoriales = [
    # (Publisher, Group, Genres, Type, Contact, Priority)
    # These rows are generated by the Literary Agent based on the project
    # PLACEHOLDER — the collaborator fills in the 10-15 publishers for the genre
]

# Validations
dv_prioridad = DataValidation(type="list", formula1='"High,Medium,Low"', allow_blank=True)
dv_tipo_resp = DataValidation(type="list", formula1='"—,Rejection,Partial,Full manuscript,Revision requested"', allow_blank=True)
dv_contrato  = DataValidation(type="list", formula1='"—,Sent,Negotiating,Signed,Rejected"', allow_blank=True)
dv_aceptado  = DataValidation(type="list", formula1='"—,Yes,No"', allow_blank=True)
dv_tipo_contacto = DataValidation(type="list", formula1='"Direct email,Web form,Agent required"', allow_blank=True)

for dv in [dv_prioridad, dv_tipo_resp, dv_contrato, dv_aceptado, dv_tipo_contacto]:
    ws.add_data_validation(dv)

for row_idx, row_data in enumerate(editoriales, start=4):
    fill = ALT_FILL if row_idx % 2 == 0 else PatternFill("solid", fgColor="FFFFFF")
    for col_idx, value in enumerate(row_data + ("—", "", "", "—", "—", "—", "—", ""), start=1):
        cell = ws.cell(row=row_idx, column=col_idx, value=value)
        cell.font = DATA_FONT
        cell.border = border
        cell.alignment = LEFT if col_idx in (1,2,3,5,13) else CENTER
        cell.fill = fill

    dv_prioridad.sqref    += f"F{row_idx}"
    dv_tipo_contacto.sqref += f"D{row_idx}"
    dv_tipo_resp.sqref    += f"J{row_idx}"
    dv_contrato.sqref     += f"K{row_idx}"
    dv_aceptado.sqref     += f"L{row_idx}"

# ─── Second sheet: legend ────────────────────────────────────────
ws2 = wb.create_sheet("Legend")
ws2.column_dimensions["A"].width = 20
ws2.column_dimensions["B"].width = 50

leyenda = [
    ("COLUMN",            "DESCRIPTION"),
    ("Publisher",         "Name of the publishing imprint"),
    ("Group / Imprint",   "Publishing group it belongs to"),
    ("Genres",            "Genres it publishes"),
    ("Contact type",      "Direct email / Web form / Agent required"),
    ("Email / URL",       "Contact address or form URL"),
    ("Priority",          "High = your first choice · Medium = second round · Low = if all else fails"),
    ("Date sent",         "DD/MM/YYYY — when you sent the query letter"),
    ("Date resent",       "DD/MM/YYYY — follow-up if no response within 6-8 weeks"),
    ("Response",          "DD/MM/YYYY — when you received a response"),
    ("Response type",     "Rejection / Partial / Full manuscript / Revision requested"),
    ("Contract",          "Status of the negotiation if you reached this point"),
    ("Accepted",          "Yes / No — whether you ultimately signed with this publisher"),
    ("Follow-up notes",   "Editor's name, conversation details, next step"),
]

for r, (col, desc) in enumerate(leyenda, start=1):
    c1 = ws2.cell(row=r, column=1, value=col)
    c2 = ws2.cell(row=r, column=2, value=desc)
    if r == 1:
        for c in [c1, c2]:
            c.font = Font(bold=True, color="FFFFFF", name="Calibri")
            c.fill = PatternFill("solid", fgColor="1F3864")
    else:
        for c in [c1, c2]:
            c.font = Font(name="Calibri", size=10)
            c.fill = ALT_FILL if r % 2 == 0 else PatternFill("solid", fgColor="FFFFFF")
    c1.alignment = LEFT
    c2.alignment = LEFT

# ─── Third sheet: email template ────────────────────────────────
ws3 = wb.create_sheet("Follow-up email template")
ws3.column_dimensions["A"].width = 80

plantilla = [
    "TEMPLATE — FOLLOW-UP EMAIL (6-8 weeks with no response)",
    "",
    "SUBJECT: Re: [Genre] — [Title] — [Author] (follow-up)",
    "",
    "Dear [Editor's name]:",
    "",
    "I'm writing to send a brief reminder about the query letter I",
    "sent you on [date sent] regarding my novel [Title],",
    "a [genre] of [N] words.",
    "",
    "I understand you receive many manuscripts and that response times",
    "are long. If the project doesn't fit [Publisher]'s current catalog,",
    "I would appreciate it if you could let me know so I can continue the process.",
    "",
    "I remain at your disposal for any questions.",
    "",
    "Sincerely,",
    "[Author's name]",
    "[Email] · [Web]",
    "",
    "---",
    "NOTE: always wait 6-8 weeks before the first follow-up.",
    "Maximum 2 follow-ups per publisher. After that, assume tacit rejection.",
]

for r, text in enumerate(plantilla, start=1):
    cell = ws3.cell(row=r, column=1, value=text)
    if r == 1:
        cell.font = Font(bold=True, size=11, color="1F3864", name="Calibri")
    else:
        cell.font = Font(size=10, name="Calibri")
    cell.alignment = LEFT

wb.save(EXCEL_OUT)
print(f"✓ Excel saved: {EXCEL_OUT}")
